---
- hosts: all
  become: true
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Remove conflicting containerd package
      apt:
        name: containerd
        state: absent
      ignore_errors: yes

    - name: Remove existing Docker packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
      ignore_errors: yes

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker apt repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present