---
- hosts: all
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Minikube dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - conntrack

    - name: Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker apt repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Install Minikube
      shell: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

    - name: Start Minikube
      shell: minikube start

    - name: Load Docker image into Minikube
      shell: minikube image load data-analytics-app:latest

    - name: Apply Kubernetes deployment
      command: kubectl apply -f /path/to/k8s/deployment.yaml

    - name: Apply Kubernetes service
      command: kubectl apply -f /path/to/k8s/service.yaml
